Catch all redis errors and report without dying
It's imperative that tagalog's command line tools not die due to connection or
redis errors. Before this change, an out-of-memory redis instance would cause a
ResponseError to be raised:

    redis.exceptions.ResponseError: command not allowed when used memory >
'maxmemory'

Now all kinds of exception from the redis client are intercepted, reported, and
should not cause tagalog to die.